# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CommunityAdmin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommunityAdmin
  pod 'kmpApp', :path => '../kmpApp'

  target 'CommunityAdminTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CommunityAdminUITests' do
    # Pods for testing
  end

end
